GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlByYW5hdiIsImlhdCI6MTY2NzA4MzI4MCwiZXhwIjoxNjY3MDgzMjk1fQ._52hasKbQnZxb7SxT_HZvTKuY6Jnc71W9c9kfn8H5lo

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "userName" : "Pranav"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlByYW5hdiIsImlhdCI6MTY2NzA4MzI3Mn0.kkwYHjlEBpCpgBAjp6mubdVUxFjGBUkchpODE-g3NGQ"
}